
import React from 'react';
import { motion } from 'framer-motion';
import { ArrowLeft, Shield, Scale, AlertTriangle, Gavel, FileSignature, Users } from 'lucide-react';

interface TermsOfServicePageProps {
  onBack: () => void;
}

export const TermsOfServicePage = ({ onBack }: TermsOfServicePageProps) => {
  return (
    <div className="min-h-screen bg-white text-gray-900 font-sans selection:bg-indigo-100 selection:text-indigo-900">
      
      {/* Navigation Bar */}
      <nav className="fixed top-0 left-0 right-0 h-16 bg-white/80 backdrop-blur-md border-b border-gray-100 z-50 flex items-center justify-between px-6 md:px-12">
        <div className="flex items-center gap-2 cursor-pointer" onClick={onBack}>
           <div className="w-8 h-8 bg-indigo-600 rounded-lg flex items-center justify-center text-white">
              <Shield size={16} />
           </div>
           <span className="font-serif font-bold text-lg">Compliee</span>
        </div>
        <button 
          onClick={onBack}
          className="flex items-center gap-2 text-sm font-medium text-gray-500 hover:text-gray-900 transition-colors bg-gray-100 hover:bg-gray-200 px-4 py-2 rounded-full"
        >
          <ArrowLeft size={16} />
          <span>Back to Home</span>
        </button>
      </nav>

      <main className="container mx-auto px-6 max-w-4xl pt-32 pb-20">
         <motion.div 
           initial={{ opacity: 0, y: 20 }}
           animate={{ opacity: 1, y: 0 }}
           transition={{ duration: 0.6 }}
        >
            <span className="text-indigo-600 font-semibold tracking-wider uppercase text-xs mb-4 block">
              Legal
            </span>
            <h1 className="text-4xl md:text-5xl font-serif text-gray-900 mb-8 leading-tight">Terms of Service</h1>
            <p className="text-gray-500 mb-12 text-lg">Last Updated: October 24, 2026</p>
            
            <div className="prose prose-lg prose-indigo text-gray-600 max-w-none">
                <div className="bg-amber-50 border border-amber-200 p-6 rounded-xl my-8">
                    <h4 className="flex items-center gap-2 text-amber-800 font-bold text-lg mb-2">
                        <AlertTriangle size={20} />
                        Crucial Disclaimer: Not Legal Advice
                    </h4>
                    <p className="text-amber-900/80 text-sm leading-relaxed m-0">
                        Compliee is an AI-powered drafting assistant, not a law firm. The documents, summaries, and risk assessments generated by our Service are for informational purposes only and do not constitute legal advice, attorney-client privilege, or a guarantee of regulatory compliance. You should always have generated documents reviewed by qualified legal counsel or a compliance officer before implementation.
                    </p>
                </div>

                <h3 className="text-gray-900 mt-8 mb-4 flex items-center gap-2 text-2xl font-serif">
                    <FileSignature size={24} className="text-indigo-600"/> 1. Acceptance of Terms
                </h3>
                <p>
                    By creating an account, accessing, or using Compliee (the "Service"), you agree to be bound by these Terms of Service ("Terms"). If you differ with these terms, you may not access the Service. You represent that you are at least 18 years old and have the authority to bind any entity for which you use the Service.
                </p>

                <h3 className="text-gray-900 mt-8 mb-4 flex items-center gap-2 text-2xl font-serif">
                    <Users size={24} className="text-indigo-600"/> 2. User Accounts & Security
                </h3>
                <p>
                    You are responsible for maintaining the confidentiality of your account credentials (provided via Puter.js authentication). You agree to notify us immediately of any unauthorized use of your account. Compliee is not liable for any loss or damage arising from your failure to protect your credentials.
                </p>

                <h3 className="text-gray-900 mt-8 mb-4 flex items-center gap-2 text-2xl font-serif">
                    <Scale size={24} className="text-indigo-600"/> 3. Intellectual Property & Data Rights
                </h3>
                <ul className="list-disc pl-6 space-y-2 mb-6">
                    <li><strong>Your Content:</strong> You retain ownership of all documents, text, and data you upload or create using Compliee. You grant us a limited, non-exclusive license to host, process, and display this content solely to provide the Service to you.</li>
                    <li><strong>Generated Content:</strong> To the extent permitted by law, you own the rights to the output generated by the AI on your behalf. Compliee assigns all right, title, and interest in such output to you.</li>
                    <li><strong>Our IP:</strong> The Compliee platform, interface, code, and branding are the sole property of Compliee Inc.</li>
                </ul>

                <h3 className="text-gray-900 mt-8 mb-4 flex items-center gap-2 text-2xl font-serif">
                    <Shield size={24} className="text-indigo-600"/> 4. Acceptable Use
                </h3>
                <p>You agree not to use the Service to:</p>
                <ul className="list-disc pl-6 space-y-2 mb-6">
                    <li>Generate fraudulent, deceptive, or illegal legal documents.</li>
                    <li>Attempt to reverse engineer the AI models or scrape data from the platform.</li>
                    <li>Draft policies intended to evade regulatory enforcement or facilitate non-compliance.</li>
                    <li>Transmit viruses, malware, or harmful code.</li>
                </ul>

                <h3 className="text-gray-900 mt-8 mb-4 text-2xl font-serif">5. AI Limitations & Liability</h3>
                <p>
                    The Service uses advanced Artificial Intelligence (Google Gemini and Mistral models) to draft content. AI can hallucinate, omit critical legal nuances, or generate outdated information.
                </p>
                <p>
                    <strong>Limitation of Liability:</strong> TO THE MAXIMUM EXTENT PERMITTED BY LAW, COMPLIEE INC. SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUE, WHETHER INCURRED DIRECTLY OR INDIRECTLY, ARISING FROM YOUR USE OF THE SERVICE OR RELIANCE ON GENERATED CONTENT.
                </p>

                <h3 className="text-gray-900 mt-8 mb-4 text-2xl font-serif">6. Termination</h3>
                <p>
                    We reserve the right to suspend or terminate your access to the Service at our sole discretion, without notice, for conduct that we believe violates these Terms or is harmful to other users, us, or third parties, or for any other reason.
                </p>

                <h3 className="text-gray-900 mt-8 mb-4 flex items-center gap-2 text-2xl font-serif">
                    <Gavel size={24} className="text-indigo-600"/> 7. Governing Law
                </h3>
                <p>
                    These Terms shall be governed by and construed in accordance with the laws of the State of California, without regard to its conflict of law principles. Any legal action or proceeding arising under these Terms will be brought exclusively in the federal or state courts located in San Francisco, California.
                </p>

                <h3 className="text-gray-900 mt-8 mb-4 text-2xl font-serif">8. Contact</h3>
                <p>
                    For legal inquiries or notices regarding these Terms, please contact:<br/>
                    <a href="mailto:o88gfdde@gmail.com" className="text-indigo-600 hover:underline font-medium">o88gfdde@gmail.com</a>
                </p>
            </div>
        </motion.div>
      </main>
    </div>
  );
};
